# Generated by Django 5.0.4 on 2024-04-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
