# Generated by Django 5.0.4 on 2024-04-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
