# Generated by Django 5.0.4 on 2024-04-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helprequest', '0002_rename_user_id_helprequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='user',
            new_name='user_id',
        ),
    ]
