# Generated by Django 5.0.4 on 2024-04-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_category_helprequest_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_image',
            field=models.CharField(max_length=200),
        ),
    ]
