# Generated by Django 5.0.4 on 2024-04-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_document_doc_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='HelpRequest',
        ),
    ]
