# Generated by Django 5.0.4 on 2024-04-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='user_id',
            new_name='user',
        ),
    ]
